spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hello
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect